add UT with vitest:ui
AgoraIO-Extensions/agora-rtc-react pull request #4
Opened 2023-04-27 11:25 UTC by guoxianzhe

chore:add patches to fix vitest types error

2023-05-12 02:22 UTC, LichKing-2234 commented
需要添加UT对应的Action check

2023-05-12 02:22 UTC, LichKing-2234 requested changes
需要添加UT对应的Action check

2023-05-12 02:22 UTC, LichKing-2234 commented on packages/agora-rtc-react/src/components/CameraVideoTrack.tsx
> +      track.setDevice(deviceId);
这里的catch去掉的原因是什么

2023-05-14 08:23 UTC, guoxianzhe commented
test ci & github comment  done
pls review again @LichKing-2234

2023-05-15 02:49 UTC, guoxianzhe commented on packages/agora-rtc-react/src/components/CameraVideoTrack.tsx
> +      track.setDevice(deviceId);
already rolled back

2023-05-15 02:57 UTC, LichKing-2234 approved these changes

2023-05-15 02:57 UTC, merged